---
username: trace
ansible_host: 34.150.172.59
ssh_pubkey: ~/.ssh/id_rsa.pub
domain: test.tracecloud.us
website_files:
    - index.html
    - styles.css
    - banner-background.jpg
    - contact.html
    - pricing.html
    - features.html
host: nginx