---
- name: Add and configure the web server user
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    ansible_user: ubuntu

  tasks:
    - name: Create user '{{ username }}'
      ansible.builtin.user:
        name: '{{ username }}'
        state: present
        createhome: yes

    - name: Add '{{ username }}' to sudoers group
      ansible.builtin.user:
        name: '{{ username }}'
        groups: sudo
        append: yes

    - name: Allow '{{ username }}' to use sudo without password
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'


    - name: Add SSH public key to '{{ username }}' authorized keys
      ansible.builtin.authorized_key:
        user: '{{ username }}'
        key: "{{ lookup('file', '{{ ssh_pubkey }}') }}"
        state: present

    - name: Set ownership and permissions for '{{ username }}' home directory
      ansible.builtin.file:
        path: /home/'{{ username }}'
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: '0755'
        state: directory
  